# Generated by Django 5.0 on 2023-12-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'خبرنامه', 'verbose_name_plural': 'خبرنامه '},
        ),
    ]
