# Generated by Django 5.0 on 2023-12-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allposts',
            name='comments',
        ),
        migrations.AddField(
            model_name='allposts',
            name='comments',
            field=models.ManyToManyField(null=True, related_name='post', to='myapp.comments', verbose_name='کامنت ها'),
        ),
    ]
