# Generated by Django 5.0 on 2023-12-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allposts',
            name='commentCount',
            field=models.IntegerField(blank=True, default=0, verbose_name='تعداد کامنت'),
        ),
    ]
