# Generated by Django 5.0 on 2023-12-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='parentReply',
        ),
    ]
