# Generated by Django 5.0 on 2024-01-14 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dlLastRechargeDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='dlLastRechargeDate'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dlRemainingDays',
            field=models.IntegerField(default=30, verbose_name='dlRemainingDays'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dlResetDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='dlResetDate'),
        ),
    ]
