# Generated by Django 5.0 on 2023-12-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='emailContact',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
    ]
