# Generated by Django 5.0 on 2023-12-20 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='likeCount',
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeCount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likecount', to='myapp.comments', verbose_name='تعداد لایک')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userliker', to=settings.AUTH_USER_MODEL, verbose_name='آیدی کاربر')),
            ],
        ),
    ]
