# Generated by Django 5.0 on 2023-12-14 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='updatePassword',
        ),
        migrations.DeleteModel(
            name='updateUsername',
        ),
        migrations.DeleteModel(
            name='userLogin',
        ),
        migrations.AlterModelOptions(
            name='commentreply',
            options={},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.AlterField(
            model_name='contactus',
            name='emailContact',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together={('userId', 'likeCount')},
        ),
    ]
