# Generated by Django 5.0 on 2023-12-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetLink',
        ),
    ]
