# Generated by Django 5.0 on 2024-01-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='customAvatar',
            field=models.FileField(blank=True, upload_to='custom_avatars/', verbose_name='Custom Avatar'),
        ),
    ]
