# Generated by Django 5.0 on 2024-01-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='customAvatar',
            field=models.FileField(blank=True, upload_to='images/', verbose_name='Custom Avatar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='selectedAvatar',
            field=models.FileField(blank=True, choices=[('images/avatar1.webp', 'Avatar 1'), ('images/avatar2.webp', 'Avatar 2'), ('images/avatar3.webp', 'Avatar 3'), ('images/avatar4.webp', 'Avatar 4'), ('images/avatar5.webp', 'Avatar 5'), ('images/avatar6.webp', 'Avatar 6'), ('images/avatar7.webp', 'Avatar 7'), ('images/avatar8.webp', 'Avatar 8'), ('images/avatar9.webp', 'Avatar 9'), ('images/avatar10.webp', 'Avatar 10'), ('images/avatar11.webp', 'Avatar 11')], upload_to='images/', verbose_name='Avatar'),
        ),
    ]
