# Generated by Django 5.0 on 2024-01-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bazikachoteam',
            options={'verbose_name': 'تیم بازیکاچو', 'verbose_name_plural': 'تیم بازیکاچو'},
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
