# Generated by Django 5.0 on 2023-12-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oldpolls',
            options={'verbose_name': 'نظرسنجی قبل', 'verbose_name_plural': 'نظرسنجی های قبلی'},
        ),
    ]
