# Generated by Django 5.0 on 2023-12-21 12:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_likehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeHistory',
            new_name='CommentLikeHistory',
        ),
        migrations.AlterModelOptions(
            name='commentlikehistory',
            options={'verbose_name': 'تاریخچه لایک کامنت', 'verbose_name_plural': 'تاریخچه لایک کامنت ها'},
        ),
    ]
