# Generated by Django 5.0 on 2023-12-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_allposts_comments_allposts_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allposts',
            name='numComments',
        ),
        migrations.RemoveField(
            model_name='allposts',
            name='numReplies',
        ),
        migrations.AlterField(
            model_name='allposts',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='post', to='myapp.comments', verbose_name='کامنت ها'),
        ),
    ]
