# Generated by Django 5.0 on 2023-12-26 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_subscriber_delete_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='date',
        ),
    ]
