# Generated by Django 5.0 on 2023-12-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_polls_isactive'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentreply',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='replyTo',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='commentReplies',
        ),
        migrations.AddField(
            model_name='commentreply',
            name='replyTo',
            field=models.ManyToManyField(related_name='comment_replies', to='myapp.comments', verbose_name='پاسخ برای'),
        ),
    ]
