# Generated by Django 5.0 on 2024-01-14 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customuser_dllastrechargedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dlExpirationDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='dlExpirationDate'),
        ),
    ]
