# Generated by Django 5.0 on 2023-12-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_allposts_commentcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='allposts',
            name='replyCount',
            field=models.IntegerField(blank=True, default=0, verbose_name='تعداد ریپلای'),
        ),
    ]
