# Generated by Django 5.0 on 2023-12-14 16:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_updatepassword_delete_updateusername_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentreply',
            options={'verbose_name': 'پاسخ', 'verbose_name_plural': 'پاسخ ها'},
        ),
        migrations.AlterUniqueTogether(
            name='commentreply',
            unique_together={('userId', 'likeCount')},
        ),
    ]
