# Generated by Django 5.0 on 2024-01-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser_customavatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='avatar',
            new_name='selectedAvatar',
        ),
    ]
