# Generated by Django 5.0 on 2024-01-13 21:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_customuser_name_customuser_customavatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='resetDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ آخرین اتمام تعداد دانلودها'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='soundtrackDownloads',
            field=models.IntegerField(default=3, verbose_name='تعداد دانلود باقی\u200cمانده موسیقی'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wallpaperDownloads',
            field=models.IntegerField(default=3, verbose_name='تعداد دانلود باقی\u200cمانده والپیپر'),
        ),
    ]
