# Generated by Django 5.0 on 2024-01-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contactus_createdat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replyreport',
            options={'verbose_name': 'گزارش ریپلای', 'verbose_name_plural': 'ریپلای های گزارش شده'},
        ),
    ]
