# Generated by Django 5.0 on 2023-12-20 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_comments_likecount_commentlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentlike',
            options={'verbose_name': 'لایک کامنت ها', 'verbose_name_plural': 'لایک کامنت ها'},
        ),
        migrations.AddField(
            model_name='commentlike',
            name='commentId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='likecount', to='myapp.comments', verbose_name='آیدی کامنت'),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='likeCount',
            field=models.IntegerField(default=0, verbose_name='تعداد لایک'),
        ),
    ]
