# Generated by Django 5.0 on 2023-12-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_oldpolls_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldpolls',
            name='expiryTimestamp',
        ),
        migrations.AddField(
            model_name='polls',
            name='endTime',
            field=models.CharField(default='24:00:00', max_length=8),
        ),
        migrations.AlterField(
            model_name='polls',
            name='expiryTimestamp',
            field=models.DateField(verbose_name=' تاریخ  اتمام نظرسنجی'),
        ),
    ]
