# Generated by Django 5.0 on 2023-12-20 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_reply_parentreplyid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlike',
            old_name='commentId',
            new_name='likeCounter',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='commentId',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='likeCount',
        ),
        migrations.AlterField(
            model_name='reply',
            name='parentReplyId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp.reply', verbose_name='ریپلای والد'),
        ),
    ]
