# Generated by Django 5.0 on 2023-12-18 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_allposts_numcomments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='parentId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp.comments'),
        ),
    ]
