# Generated by Django 5.0 on 2023-12-15 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_commentreply_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='polls',
        ),
        migrations.AddField(
            model_name='choice',
            name='choiceNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره گزینه '),
        ),
        migrations.AddField(
            model_name='oldpolls',
            name='choices',
            field=models.ManyToManyField(to='myapp.choice', verbose_name='گزینه ها'),
        ),
        migrations.AddField(
            model_name='polls',
            name='choices',
            field=models.ManyToManyField(to='myapp.choice', verbose_name='گزینه ها'),
        ),
        migrations.AlterField(
            model_name='bazi100team',
            name='username',
            field=models.CharField(help_text="Usernames can contain letters(a-z),numbers(0-9),and periods(.).Usernames cannot contain an ampersand(&),equals sings(=),underscore(_),aposterophe('),dash(-),plus sign(+),comma(,),brackets(<,>),or more than one period(.) in a row", max_length=80, unique=True, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
