# Generated by Django 5.0 on 2023-12-17 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_oldpolls_expirytimestamp_polls_endtime_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='oldPolls',
        ),
    ]
