# Generated by Django 5.0 on 2023-12-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_allposts_replycount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allposts',
            name='eventStage',
            field=models.CharField(blank=True, choices=[('e3', 'e3'), ('game-awards', 'game-awards'), ('gamescom', 'gamescom'), ('tgs', 'tgs')], max_length=100, null=True, verbose_name='برگزارکننده رویداد'),
        ),
        migrations.AlterField(
            model_name='allposts',
            name='videoType',
            field=models.CharField(blank=True, choices=[('gameplays-trailers', 'gameplays-trailers'), ('blink', 'blink')], max_length=40, null=True, verbose_name='تایپ ویدیو'),
        ),
    ]
