# Generated by Django 5.0 on 2023-12-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_likehistory_commentlikehistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='likeCount',
            field=models.IntegerField(default=0, verbose_name='تعداد لایک'),
        ),
    ]
