# Generated by Django 5.0 on 2024-01-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customuser_resetdate_customuser_soundtrackdownloads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='downloadType',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='soundtrackDownloads',
            field=models.IntegerField(default=3, verbose_name='soundtrack_dl_remain'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='wallpaperDownloads',
            field=models.IntegerField(default=3, verbose_name='wallpaper_dl_remain'),
        ),
    ]
