# Generated by Django 5.0 on 2023-12-18 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_commentreply_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='parentComment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp.comments'),
        ),
        migrations.DeleteModel(
            name='commentReply',
        ),
    ]
