# Generated by Django 5.0 on 2024-01-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customuser_dlexpirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='zipFile',
            field=models.TextField(verbose_name='فایل زیپ'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='audioFile',
            field=models.TextField(verbose_name='فایل موسیقی'),
        ),
        migrations.AlterField(
            model_name='wallpapers',
            name='image',
            field=models.TextField(null=True, verbose_name='فایل والپیپر'),
        ),
    ]
