# Generated by Django 5.0 on 2023-12-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_commentid_commentlike_likecounter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='likeCount',
            field=models.IntegerField(default=0, verbose_name='تعداد لایک'),
        ),
        migrations.DeleteModel(
            name='commentLike',
        ),
    ]
