# Generated by Django 5.0 on 2023-12-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_comments_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allposts',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='post', to='myapp.comments', verbose_name='کامنت ها'),
        ),
    ]
