# Generated by Django 5.0 on 2023-12-25 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_subscriber_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='subscribed_at',
            new_name='createdAt',
        ),
    ]
