# Generated by Django 5.0 on 2023-12-15 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_choice_polls_choice_choicenumber_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='numvotes',
            new_name='numVotes',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choiceNumber',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='user',
        ),
        migrations.AlterField(
            model_name='oldpolls',
            name='expiryTimestamp',
            field=models.DateTimeField(verbose_name=' تاریخ و ساعت اتمام نظرسنجی'),
        ),
        migrations.AlterField(
            model_name='polls',
            name='expiryTimestamp',
            field=models.DateTimeField(verbose_name=' تاریخ و ساعت اتمام نظرسنجی'),
        ),
        migrations.CreateModel(
            name='vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.choice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رای ها',
                'verbose_name_plural': 'رای ها',
            },
        ),
    ]
