# Generated by Django 5.0 on 2024-01-16 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_albums_zipfile_alter_tracks_audiofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dlExpirationDate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='dlLastRechargeDate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='dlRemainingDays',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='dlResetDate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='downloadType',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='soundtrackDownloads',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='wallpaperDownloads',
        ),
    ]
